### ISSUE TITLE
USER STORY: Submit a poll response

### ISSUE THREAD

**Issue by mariaciceri** [mariaciceri/love-running-practice#1]
In order to **provide my opinion about a certain running topic or event** as a **user**, I can **submit an answer from the poll**

## Acceptance Criteria
- The user can interact with the poll;
- The user can comment on the poll;
- The user can submit their comment;

## Tasks

- [ ] Update the page to have a poll section;
- [ ] Create a comment area and a submit button;
- [ ] Have the user's name displayed with the comment;
- [ ] Test the functionality;
