### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by mariaciceri** [mariaciceri/love-running-practice#2]
In order to **collect users feedback** as a **admin**, I can **publish a poll**

## Acceptance Criteria
- The admin can post a poll;
- The poll is accessible for all users to interact with;
- The admin can access results from the poll;

## Tasks

- [ ] Create a button to add a new poll only accessible by the admin;
- [ ] Create a form that will be filled with the question for the poll;
- [ ] Update the page with the newly created poll;
- [ ] Create an easy way to access the poll's results;
- [ ] Test the functionality;

**Comment by mariaciceri** [comment]
this is completed
